"""Pre-built demo cases for the interactive banking demo.

Uses fact-based format for toggleable UI controls.
Each fact can be boolean, number, or string for different input types.
"""

DEMO_CASES = [
    # ============== PASS CASES (Should NOT escalate) ==============
    {
        "id": "pep-legal-fees",
        "name": "Foreign PEP - Legal Fees (EDGE)",
        "description": "Italian minister paying London law firm. PEP status triggers EDD by classifier sovereignty — no STR without behavioral suspicion.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["PEP flag Y", "Docs verified", "High tenure"],
        "facts": [
            {"field": "customer.pep_flag", "value": True, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "IT", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 265000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "GB", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 95, "label": "Match Score"},
            {"field": "screening.list_type", "value": "PEP", "label": "List Type"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 22, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Legal fees - retained counsel", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
        ]
    },
    {
        "id": "high-value-explained",
        "name": "High Value Wire - Documented (PASS)",
        "description": "Large corporate wire with complete documentation. Amount alone cannot trigger.",
        "category": "PASS",
        "expected_outcome": "pass",
        "key_facts": ["$2.5M wire", "Docs complete", "Long-term customer"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 2500000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": True, "label": "Beneficial Ownership Clear"},
            {"field": "relationship.tenure_years", "value": 15, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Business acquisition payment", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ]
    },
    {
        "id": "cross-border-routine",
        "name": "Cross-Border - Routine (PASS)",
        "description": "Regular cross-border payments matching historical pattern. Geography alone cannot trigger.",
        "category": "PASS",
        "expected_outcome": "pass",
        "key_facts": ["Hong Kong destination", "Family transfer", "Documented"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 25000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "HK", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 10, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Family support remittance", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
        ]
    },

    # ============== ESCALATE CASES (Should escalate) ==============
    {
        "id": "sanctions-hit",
        "name": "Sanctions Match - OFAC (ESCALATE)",
        "description": "Confirmed OFAC sanctions match. Immediate hard stop required.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["OFAC SDN match", "Score 98%", "Russian entity"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "RU", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 680000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "AE", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 98, "label": "Match Score"},
            {"field": "screening.list_type", "value": "OFAC_SDN", "label": "List Type"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "screening.sanctions_match", "value": True, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 1, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ]
    },
    {
        "id": "structuring-pattern",
        "name": "Structuring - Just Under $10K (ESCALATE)",
        "description": "Multiple cash deposits just under $10K threshold. Classic structuring pattern.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["3x cash deposits", "All ~$9,500", "Same day"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 9500, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CASH", "label": "Payment Method"},
            {"field": "transaction.count", "value": 3, "label": "Transaction Count"},
            {"field": "pattern.structuring", "value": True, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "relationship.tenure_years", "value": 3, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.purpose", "value": "Unclear - multiple cash deposits", "label": "Stated Purpose"},
        ]
    },
    {
        "id": "shell-company-layering",
        "name": "Shell Company - BVI (ESCALATE)",
        "description": "Funds moving through shell company in tax haven with unclear ownership.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["BVI entity", "Missing docs", "$1.6M wire"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "VG", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 1632000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "SG", "label": "Destination Country"},
            {"field": "pattern.layering", "value": True, "label": "Layering Pattern"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": False, "label": "Beneficial Ownership Clear"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "relationship.tenure_years", "value": 0.3, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 4, "label": "Transaction Count"},
        ]
    },

    # ============== EDGE CASES (Boundary conditions) ==============
    {
        "id": "pep-plus-adverse-media",
        "name": "PEP + Adverse Media (EDGE)",
        "description": "Foreign PEP with adverse media linking to money laundering. Tests corroboration.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["PEP flag Y", "Adverse media MLTF", "Missing docs"],
        "facts": [
            {"field": "customer.pep_flag", "value": True, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "BR", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 476000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CH", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 92, "label": "Match Score"},
            {"field": "screening.list_type", "value": "ADVERSE_MEDIA", "label": "List Type"},
            {"field": "screening.mltf_linked", "value": True, "label": "Linked to Money Laundering"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "confirmed_mltf", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": True, "label": "Adverse Media"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 4, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 2, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Investment - unclear vehicle", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ]
    },
    {
        "id": "crypto-high-risk-corridor",
        "name": "Crypto to Wire - UAE (EDGE)",
        "description": "Crypto conversion to wire through high-risk jurisdiction.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["Crypto source", "UAE destination", "Unverified funds"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 102000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CRYPTO", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "AE", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 2, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 3, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Crypto liquidation - personal", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ]
    },
    {
        "id": "velocity-spike",
        "name": "10x Velocity Spike (EDGE)",
        "description": "Long-term customer with sudden 10x increase in transaction volume.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["12yr customer", "10x volume spike", "Missing docs"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 850000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CN", "label": "Destination Country"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "pattern.multiplier", "value": 10, "label": "Volume Multiplier"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 12, "label": "Relationship Tenure (Years)"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "transaction.count", "value": 15, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Trade payments - new supplier", "label": "Stated Purpose"},
            {"field": "docs.ownership_clear", "value": True, "label": "Beneficial Ownership Clear"},
        ]
    },
    {
        "id": "beneficial-owner-pep",
        "name": "Hidden PEP Owner (EDGE)",
        "description": "Corporate entity with undisclosed PEP beneficial owner discovered in screening.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["Cyprus entity", "Hidden PEP owner", "$2.9M to Swiss bank"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Customer PEP Flag"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CY", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 2900000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CH", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 88, "label": "Match Score"},
            {"field": "screening.list_type", "value": "PEP", "label": "List Type"},
            {"field": "screening.beneficial_owner_pep", "value": True, "label": "Beneficial Owner is PEP"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": False, "label": "Beneficial Ownership Clear"},
            {"field": "relationship.tenure_years", "value": 0.5, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 2, "label": "Transaction Count"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": True, "label": "Layering Pattern"},
        ]
    },

    # ============== ADDITIONAL SCENARIOS ==============

    # ── PASS: Dormant account, low value, benign reactivation ──
    {
        "id": "dormant-account-reactivation",
        "name": "Dormant Account Reactivation (PASS)",
        "description": "Long-dormant individual account reactivated with small cash deposit. No risk indicators.",
        "category": "PASS",
        "expected_outcome": "pass",
        "key_facts": ["Dormant 18 months", "$3,200 deposit", "8-year relationship"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 3200, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CASH", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 8, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Account reactivation deposit", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── PASS: Cash-intensive business, routine LCTR ──
    {
        "id": "cash-intensive-lctr",
        "name": "Cash-Intensive Business - LCTR (PASS)",
        "description": "Restaurant depositing $15K cash. Known cash-intensive industry. Routine large cash handling.",
        "category": "PASS",
        "expected_outcome": "pass",
        "key_facts": ["Restaurant (cash-intensive)", "$15K cash deposit", "5-year relationship"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 15000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CASH", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 5, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Weekly restaurant cash deposit", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── ESCALATE: Exact sanctions match (SEMA) ──
    {
        "id": "sanctions-exact-match",
        "name": "Sanctions Exact Match - SEMA (ESCALATE)",
        "description": "Corporate wire to SEMA-listed entity. Exact match. Mandatory hard stop.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["SEMA exact match", "$50K wire", "Sanctioned jurisdiction"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 50000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "IR", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 100, "label": "Match Score"},
            {"field": "screening.list_type", "value": "SEMA", "label": "List Type"},
            {"field": "screening.sanctions_match", "value": True, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 0.5, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── EDGE: Domestic PEP, routine mortgage payment ──
    {
        "id": "domestic-pep-routine",
        "name": "Domestic PEP - Mortgage (EDGE)",
        "description": "Provincial PEP making routine mortgage payment. Long relationship, fully documented. PEP status triggers EDD by classifier sovereignty.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["Domestic PEP", "$2,800 mortgage", "12-year relationship"],
        "facts": [
            {"field": "customer.pep_flag", "value": True, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 2800, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "EFT", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 100, "label": "Match Score"},
            {"field": "screening.list_type", "value": "PEP", "label": "List Type"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 12, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Monthly mortgage payment", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── ESCALATE: Classic structuring — three same-day deposits ──
    {
        "id": "structuring-three-deposits",
        "name": "Structuring - Three Same-Day Deposits (ESCALATE)",
        "description": "New customer, three same-day cash deposits just under $10K at different branches.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["3x same-day cash", "$9.5K/$9.2K/$9.8K", "New customer (3 months)"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 9500, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CASH", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "transaction.count", "value": 3, "label": "Transaction Count"},
            {"field": "pattern.structuring", "value": True, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 0.25, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.purpose", "value": "Unclear - multiple cash deposits same day", "label": "Stated Purpose"},
        ],
    },

    # ── EDGE: Trade finance with unusual documentation ──
    {
        "id": "trade-finance-unusual-docs",
        "name": "Trade Finance - Unusual Docs (EDGE)",
        "description": "Importer LC with vague goods description and inconsistent pricing. Profile deviation.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["$2.3M letter of credit", "Vague goods description", "Pricing inconsistency"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 2300000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "TR", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 3, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Letter of credit - import goods", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "trade.goods_description", "value": "vague", "label": "Goods Description Quality"},
            {"field": "trade.pricing_consistent", "value": False, "label": "Pricing Consistent"},
            {"field": "trade.is_letter_of_credit", "value": True, "label": "Letter of Credit"},
        ],
    },

    # ── PASS: Profile deviation with complete evidence ──
    {
        "id": "profile-deviation-complete-evidence",
        "name": "Profile Deviation - Complete Evidence (PASS)",
        "description": "First international wire but all evidence present including stated purpose. Clean profile.",
        "category": "PASS",
        "expected_outcome": "pass",
        "key_facts": ["First international wire", "All 27 fields present", "Property purchase"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 45000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "PT", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 6, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Property purchase deposit - Portugal", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── EDGE: Adverse media — unconfirmed fraud investigation ──
    {
        "id": "adverse-media-unconfirmed",
        "name": "Adverse Media - Unconfirmed (EDGE)",
        "description": "News article mentioning fraud investigation. Not confirmed, no charges. Clean profile otherwise.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["Adverse media (unconfirmed)", "$75K domestic wire", "No charges filed"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 75000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.match_score", "value": 75, "label": "Match Score"},
            {"field": "screening.list_type", "value": "ADVERSE_MEDIA", "label": "List Type"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "unconfirmed", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": True, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 4, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Investment - brokerage transfer", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── ESCALATE: MSB with multiple red flags ──
    {
        "id": "multiple-flags-commercial-exit",
        "name": "MSB - Multiple Red Flags (ESCALATE)",
        "description": "Money service business with shell company indicators, rapid movement, third-party payments, and prior closure.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["MSB client", "Shell + rapid + 3rd-party", "Prior account closure"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 180000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "NG", "label": "Destination Country"},
            {"field": "pattern.layering", "value": True, "label": "Layering Pattern"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": False, "label": "Beneficial Ownership Clear"},
            {"field": "flag.shell_company", "value": True, "label": "Shell Company Indicators"},
            {"field": "flag.third_party", "value": True, "label": "Third-Party Payments"},
            {"field": "prior.account_closures", "value": True, "label": "Prior Account Closure"},
            {"field": "relationship.tenure_years", "value": 2, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 5, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Supplier payments - unclear beneficiary", "label": "Stated Purpose"},
        ],
    },

    # ── EDGE: Foreign PEP, large wire, fully documented ──
    {
        "id": "pep-foreign-large-wire-clean",
        "name": "Foreign PEP - Large Wire Clean (EDGE)",
        "description": "Senior foreign government official, $320K wire, but long relationship and fully documented diplomatic salary.",
        "category": "EDGE",
        "expected_outcome": "pass",
        "key_facts": ["Foreign PEP", "$320K wire", "Diplomatic salary documented"],
        "facts": [
            {"field": "customer.pep_flag", "value": True, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "SA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 320000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "GB", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 97, "label": "Match Score"},
            {"field": "screening.list_type", "value": "PEP", "label": "List Type"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 7, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Property management fees - London residence", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ============== BOUNDARY CONDITION CASES ==============

    # ── PEP isolation — domestic PEP, zero flags, clean path ──
    {
        "id": "pep-domestic-low-value-clean",
        "name": "Domestic PEP - Low Value Clean (EDGE)",
        "description": "Domestic PEP, under $10K, zero behavioral flags, verified source of funds, established customer. Tests PEP isolation gate.",
        "category": "EDGE",
        "expected_outcome": "pass",
        "key_facts": ["Domestic PEP", "$8K EFT", "15yr tenure", "All clean"],
        "facts": [
            {"field": "customer.pep_flag", "value": True, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 8000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "EFT", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 100, "label": "Match Score"},
            {"field": "screening.list_type", "value": "PEP", "label": "List Type"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": True, "label": "Beneficial Ownership Clear"},
            {"field": "relationship.tenure_years", "value": 15, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Monthly utility payment", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── Crypto + sanctioned destination — hard stop evaluation ──
    {
        "id": "crypto-unhosted-wallet-high-risk",
        "name": "Crypto to Sanctioned Destination (ESCALATE)",
        "description": "Crypto exchange + sanctioned destination (Iran) + velocity spike. Tests hard stop evaluation and policy regime awareness.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["Crypto method", "Iran destination", "Sanctions match", "Velocity spike"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 195000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CRYPTO", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "IR", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.match_score", "value": 95, "label": "Match Score"},
            {"field": "screening.list_type", "value": "OFAC_SDN", "label": "List Type"},
            {"field": "screening.sanctions_match", "value": True, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 0.5, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 5, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Crypto liquidation", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── Shell + layering + structuring + prior STRs — maximum escalation ──
    {
        "id": "shell-company-layering-prior-strs",
        "name": "Shell + Layering + Prior STRs (ESCALATE)",
        "description": "Shell company + layering + structuring + 2 prior STR filings + ongoing unusual activity. Terminal strong classification.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["Shell + layering + structuring", "2 prior STRs", "BVI to Cayman", "$2.1M"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "VG", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 2100000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "KY", "label": "Destination Country"},
            {"field": "pattern.structuring", "value": True, "label": "Structuring Pattern Detected"},
            {"field": "pattern.layering", "value": True, "label": "Layering Pattern"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "flag.shell_company", "value": True, "label": "Shell Company Indicators"},
            {"field": "flag.third_party", "value": True, "label": "Third-Party Payments"},
            {"field": "prior.sars_filed", "value": 2, "label": "Prior SARs Filed"},
            {"field": "prior.account_closures", "value": True, "label": "Prior Account Closure"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": False, "label": "Beneficial Ownership Clear"},
            {"field": "relationship.tenure_years", "value": 0.3, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 8, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Investment disbursement - multiple beneficiaries", "label": "Stated Purpose"},
        ],
    },

    # ── Unconfirmed adverse media, clean profile — clearable strong ──
    {
        "id": "adverse-media-generic-clean-rebuttal",
        "name": "Adverse Media - Clean Rebuttal (EDGE)",
        "description": "Generic unconfirmed adverse media, no behavioral flags, verified source, 10yr customer. Tests clearable strong override.",
        "category": "EDGE",
        "expected_outcome": "pass",
        "key_facts": ["Adverse media (unconfirmed)", "No MLTF link", "10yr tenure", "All docs clean"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 42000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.match_score", "value": 70, "label": "Match Score"},
            {"field": "screening.list_type", "value": "ADVERSE_MEDIA", "label": "List Type"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "unconfirmed", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": True, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": True, "label": "Beneficial Ownership Clear"},
            {"field": "relationship.tenure_years", "value": 10, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Tax payment - CRA installment", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── Foreign PEP + HR geo + missing purpose — administrative moderate ──
    {
        "id": "foreign-pep-hr-geo-missing-purpose",
        "name": "Foreign PEP + HR Geo + No Purpose (ESCALATE)",
        "description": "Foreign PEP + high-risk jurisdiction + missing stated purpose. No behavioral flags. Tests administrative moderate vs substantive.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["Foreign PEP", "Nigeria residence", "UAE destination", "No purpose stated"],
        "facts": [
            {"field": "customer.pep_flag", "value": True, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "NG", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 55000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "AE", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 90, "label": "Match Score"},
            {"field": "screening.list_type", "value": "PEP", "label": "List Type"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 2, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── ALLOW disposition + STR reporting — two-axis split ──
    {
        "id": "allow-with-str-controlled-delivery",
        "name": "Allow + STR Controlled Delivery (EDGE)",
        "description": "Transaction allowed despite suspicion (controlled delivery). STR filed. Tests ALLOW/STR two-axis combination.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["Structuring", "Prior STR", "Confirmed MLTF", "8yr tenure"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 47000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "pattern.structuring", "value": True, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "prior.sars_filed", "value": 1, "label": "Prior SARs Filed"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.match_score", "value": 85, "label": "Match Score"},
            {"field": "screening.list_type", "value": "ADVERSE_MEDIA", "label": "List Type"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "confirmed_mltf", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": True, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": True, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 8, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 2, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Investment transfer - brokerage", "label": "Stated Purpose"},
        ],
    },

    # ── Zero flags, established customer — absolute baseline ──
    {
        "id": "zero-flags-established-customer",
        "name": "Zero Flags - Established Customer (PASS)",
        "description": "20yr customer, all flags false, domestic, low value, clean screening. Absolute baseline — should produce ALLOW/NO_REPORT.",
        "category": "PASS",
        "expected_outcome": "pass",
        "key_facts": ["Zero flags", "20yr tenure", "$1,500 EFT", "All clean"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 1500, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "EFT", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": True, "label": "Beneficial Ownership Clear"},
            {"field": "relationship.tenure_years", "value": 20, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Monthly bill payment", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── Everything adverse — maximum conviction ──
    {
        "id": "everything-adverse",
        "name": "Everything Adverse - Maximum Flags (ESCALATE)",
        "description": "Foreign PEP + confirmed MLTF + shell + layering + structuring + prior STRs + sanctions + HR geo. Maximum adversity.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["Foreign PEP + sanctions + MLTF", "Shell + layering + structuring", "4 prior STRs", "$4.8M"],
        "facts": [
            {"field": "customer.pep_flag", "value": True, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "RU", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 4800000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "KY", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 99, "label": "Match Score"},
            {"field": "screening.list_type", "value": "OFAC_SDN", "label": "List Type"},
            {"field": "screening.match_count", "value": 3, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": True, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "confirmed_mltf", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": True, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": True, "label": "Linked to Money Laundering"},
            {"field": "screening.beneficial_owner_pep", "value": True, "label": "Beneficial Owner is PEP"},
            {"field": "pattern.structuring", "value": True, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": True, "label": "Layering Pattern"},
            {"field": "flag.shell_company", "value": True, "label": "Shell Company Indicators"},
            {"field": "flag.third_party", "value": True, "label": "Third-Party Payments"},
            {"field": "prior.sars_filed", "value": 4, "label": "Prior SARs Filed"},
            {"field": "prior.account_closures", "value": True, "label": "Prior Account Closure"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": False, "label": "Beneficial Ownership Clear"},
            {"field": "relationship.tenure_years", "value": 0.1, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 12, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Unclear - rapid movement through multiple entities", "label": "Stated Purpose"},
        ],
    },

    # ============== POOL DIVERSITY CASES ==============

    # ── First case new policy regime — zero post-shift precedents ──
    {
        "id": "first-case-new-policy-regime",
        "name": "First Case Under New Policy (EDGE)",
        "description": "Novel case profile under recent policy shift. Zero post-shift precedents. Tests first-of-kind warning and confidence impact.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["Novel profile", "Crypto + trade finance", "Vague goods", "No prior comparable"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 340000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CRYPTO", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "SG", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": False, "label": "Beneficial Ownership Clear"},
            {"field": "relationship.tenure_years", "value": 1, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 3, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Crypto-settled trade payment", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "trade.goods_description", "value": "vague", "label": "Goods Description Quality"},
            {"field": "trade.pricing_consistent", "value": False, "label": "Pricing Consistent"},
            {"field": "trade.is_letter_of_credit", "value": False, "label": "Letter of Credit"},
        ],
    },

    # ── All precedents non-transferable ──
    {
        "id": "all-precedents-non-transferable",
        "name": "All Precedents Non-Transferable (EDGE)",
        "description": "Case where comparable pool exists but matches have contradicting drivers. Tests transferable count=0, effective pool messaging.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["Corp + layering", "Cross-border HR", "Driver contradictions expected"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "HK", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 780000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "VG", "label": "Destination Country"},
            {"field": "pattern.layering", "value": True, "label": "Layering Pattern"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "flag.shell_company", "value": True, "label": "Shell Company Indicators"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": False, "label": "Beneficial Ownership Clear"},
            {"field": "relationship.tenure_years", "value": 0.8, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 6, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Intercompany transfer - restructuring", "label": "Stated Purpose"},
        ],
    },

    # ── Single comparable precedent ──
    {
        "id": "single-comparable-precedent",
        "name": "Single Comparable Precedent (EDGE)",
        "description": "Unusual profile yielding exactly 1 comparable precedent above threshold. Tests pool adequacy=LOW, alignment on pool of 1.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["Rare profile", "Trade finance + crypto", "Single match expected"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 125000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CRYPTO", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "TR", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "unconfirmed", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": True, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 1.5, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 2, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Crypto-settled import payment", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "trade.goods_description", "value": "vague", "label": "Goods Description Quality"},
            {"field": "trade.pricing_consistent", "value": False, "label": "Pricing Consistent"},
            {"field": "trade.is_letter_of_credit", "value": True, "label": "Letter of Credit"},
        ],
    },

    # ── Classifier STR, all precedents NO_REPORT ──
    {
        "id": "classifier-str-all-precedents-no-report",
        "name": "Classifier STR vs All-Clear Pool (EDGE)",
        "description": "Classifier says STR_REQUIRED but comparable precedents all resolved NO_REPORT. Tests precedent deviation flag and conflict.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["Confirmed MLTF", "Structuring", "But clean pool history"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 28000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CASH", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "pattern.structuring", "value": True, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.match_score", "value": 80, "label": "Match Score"},
            {"field": "screening.list_type", "value": "ADVERSE_MEDIA", "label": "List Type"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "confirmed_mltf", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": True, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": True, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 6, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 2, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Cash deposit - business revenue", "label": "Stated Purpose"},
        ],
    },

    # ── Classifier NO_REPORT, half precedents STR ──
    {
        "id": "classifier-no-report-half-str",
        "name": "Classifier Clear vs Mixed STR Pool (EDGE)",
        "description": "Classifier says NO_REPORT but 50% of comparable precedents filed STR. Tests low confidence from outcome inconsistency.",
        "category": "EDGE",
        "expected_outcome": "pass",
        "key_facts": ["Clean profile", "Domestic wire", "But similar profiles have STR history"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 95000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": True, "label": "Beneficial Ownership Clear"},
            {"field": "relationship.tenure_years", "value": 4, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Vendor payment - consulting services", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── Mixed undetermined/determined pool ──
    {
        "id": "mixed-undetermined-determined-pool",
        "name": "Mixed Determined/Undetermined Pool (EDGE)",
        "description": "Case where comparable pool has mix of determined (STR/NO_REPORT) and undetermined reporting. Tests partial regulatory alignment.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["PEP + cross-border", "Mixed pool expected", "Partial regulatory data"],
        "facts": [
            {"field": "customer.pep_flag", "value": True, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "MX", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 165000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "PA", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 88, "label": "Match Score"},
            {"field": "screening.list_type", "value": "PEP", "label": "List Type"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 3, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 2, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Property investment - Panama", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ============== TYPOLOGY + NARRATIVE CASES ==============

    # ── Forming typology, strong classifier signal ──
    {
        "id": "forming-typology-strong-classifier",
        "name": "Forming Typology + Strong Signal (ESCALATE)",
        "description": "Typology is FORMING but classifier signal is very strong (multiple indicators). Tests Gate 1 sovereignty over classifier.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["Velocity spike + adverse media", "But no structuring/layering", "FORMING stage"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 210000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "AE", "label": "Destination Country"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.match_score", "value": 78, "label": "Match Score"},
            {"field": "screening.list_type", "value": "ADVERSE_MEDIA", "label": "List Type"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "confirmed", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": True, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 3, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 4, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Business expansion - consultancy fees", "label": "Stated Purpose"},
        ],
    },

    # ── Established typology, weak evidence ──
    {
        "id": "established-typology-weak-evidence",
        "name": "Established Typology - Weak Evidence (EDGE)",
        "description": "Typology is ESTABLISHED (structuring) but evidence is thin — only 1 indicator. Tests corroboration requirements.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["Structuring detected", "But single indicator only", "Docs complete"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 9800, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CASH", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "pattern.structuring", "value": True, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 7, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Cash deposit - personal savings", "label": "Stated Purpose"},
        ],
    },

    # ── Multiple typologies — shell company + structuring ──
    {
        "id": "multiple-typologies-same-case",
        "name": "Multiple Typologies - Shell + Structuring (ESCALATE)",
        "description": "Case triggers both shell company and structuring typology families. Tests multi-typology handling.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["Shell company + structuring", "Cross-border", "New customer"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 485000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "VG", "label": "Destination Country"},
            {"field": "pattern.structuring", "value": True, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": True, "label": "Layering Pattern"},
            {"field": "flag.shell_company", "value": True, "label": "Shell Company Indicators"},
            {"field": "flag.third_party", "value": True, "label": "Third-Party Payments"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": False, "label": "Beneficial Ownership Clear"},
            {"field": "relationship.tenure_years", "value": 0.4, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 7, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Investment disbursement - offshore fund", "label": "Stated Purpose"},
        ],
    },

    # ── Near-threshold typology — one indicator short ──
    {
        "id": "near-threshold-typology",
        "name": "Near Threshold Typology (EDGE)",
        "description": "One additional indicator would shift typology from FORMING to ESTABLISHED. Tests boundary precision.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["Velocity spike only", "HR destination", "Missing docs"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 72000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "NG", "label": "Destination Country"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 2, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 3, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Personal transfer - family", "label": "Stated Purpose"},
        ],
    },

    # ── No typology, pure obligation (LCTR) ──
    {
        "id": "no-typology-pure-obligation",
        "name": "No Typology - Pure LCTR Obligation (PASS)",
        "description": "Cash over $10K triggers LCTR filing obligation. No suspicious typology. Tests obligation without suspicion.",
        "category": "PASS",
        "expected_outcome": "pass",
        "key_facts": ["$12K cash (LCTR trigger)", "No flags", "Known business customer"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 12000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CASH", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": True, "label": "Beneficial Ownership Clear"},
            {"field": "relationship.tenure_years", "value": 9, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Weekly cash deposit - retail store", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── Duplicate indicator names from different sources ──
    {
        "id": "duplicate-indicator-names",
        "name": "Duplicate Indicators - Multi-Source (ESCALATE)",
        "description": "Same adverse media indicator from both screening system and manual review. Tests deduplication and signal count accuracy.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["Adverse media (dual source)", "PEP", "Cross-border HR"],
        "facts": [
            {"field": "customer.pep_flag", "value": True, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "BR", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 310000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CH", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 91, "label": "Match Score"},
            {"field": "screening.list_type", "value": "ADVERSE_MEDIA", "label": "List Type"},
            {"field": "screening.match_count", "value": 2, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "confirmed", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": True, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 5, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 2, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Investment - real estate fund", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },
]


def get_demo_cases() -> list[dict]:
    """Return all demo cases for list view."""
    return [{
        "id": c["id"],
        "name": c["name"],
        "description": c["description"],
        "category": c["category"],
        "expected_verdict": c.get("expected_outcome", "unknown"),
        "expected_outcome": c.get("expected_outcome", "unknown"),
        "key_levers": c.get("key_facts", []),
        "key_facts": c.get("key_facts", []),
        "tags": [c["category"].lower()],
        "facts": [
            {"field_id": f["field"], "field": f["field"], "value": f["value"], "label": f.get("label", f["field"])}
            for f in c["facts"]
        ],
    } for c in DEMO_CASES]


def get_demo_case(case_id: str) -> dict | None:
    """Get a specific demo case by ID."""
    for case in DEMO_CASES:
        if case["id"] == case_id:
            return {
                "id": case["id"],
                "name": case["name"],
                "description": case["description"],
                "category": case["category"],
                "expected_verdict": case.get("expected_outcome", "unknown"),
                "expected_outcome": case.get("expected_outcome", "unknown"),
                "key_levers": case.get("key_facts", []),
                "key_facts": case.get("key_facts", []),
                "tags": [case["category"].lower()],
                "facts": [
                    {"field_id": f["field"], "field": f["field"], "value": f["value"], "label": f.get("label", f["field"])}
                    for f in case["facts"]
                ],
            }
    return None


def get_demo_cases_by_category(category: str) -> list[dict]:
    """Get demo cases filtered by category."""
    return [c for c in DEMO_CASES if c["category"] == category]
