"""Pre-built demo cases for the interactive banking demo.

Uses fact-based format for toggleable UI controls.
Each fact can be boolean, number, or string for different input types.
"""

DEMO_CASES = [
    # ============== PASS CASES (Should NOT escalate) ==============
    {
        "id": "pep-legal-fees",
        "name": "Foreign PEP - Legal Fees (EDGE)",
        "description": "Italian minister paying London law firm. PEP status triggers EDD by classifier sovereignty — no STR without behavioral suspicion.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["PEP flag Y", "Docs verified", "High tenure"],
        "facts": [
            {"field": "customer.pep_flag", "value": True, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "IT", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 265000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "GB", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 95, "label": "Match Score"},
            {"field": "screening.list_type", "value": "PEP", "label": "List Type"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 22, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Legal fees - retained counsel", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
        ]
    },
    {
        "id": "high-value-explained",
        "name": "High Value Wire - Documented (PASS)",
        "description": "Large corporate wire with complete documentation. Amount alone cannot trigger.",
        "category": "PASS",
        "expected_outcome": "pass",
        "key_facts": ["$2.5M wire", "Docs complete", "Long-term customer"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 2500000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": True, "label": "Beneficial Ownership Clear"},
            {"field": "relationship.tenure_years", "value": 15, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Business acquisition payment", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ]
    },
    {
        "id": "cross-border-routine",
        "name": "Cross-Border - Routine (PASS)",
        "description": "Regular cross-border payments matching historical pattern. Geography alone cannot trigger.",
        "category": "PASS",
        "expected_outcome": "pass",
        "key_facts": ["Hong Kong destination", "Family transfer", "Documented"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 25000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "HK", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 10, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Family support remittance", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
        ]
    },

    # ============== ESCALATE CASES (Should escalate) ==============
    {
        "id": "sanctions-hit",
        "name": "Sanctions Match - OFAC (ESCALATE)",
        "description": "Confirmed OFAC sanctions match. Immediate hard stop required.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["OFAC SDN match", "Score 98%", "Russian entity"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "RU", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 680000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "AE", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 98, "label": "Match Score"},
            {"field": "screening.list_type", "value": "OFAC_SDN", "label": "List Type"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "screening.sanctions_match", "value": True, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 1, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ]
    },
    {
        "id": "structuring-pattern",
        "name": "Structuring - Just Under $10K (ESCALATE)",
        "description": "Multiple cash deposits just under $10K threshold. Classic structuring pattern.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["3x cash deposits", "All ~$9,500", "Same day"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 9500, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CASH", "label": "Payment Method"},
            {"field": "transaction.count", "value": 3, "label": "Transaction Count"},
            {"field": "pattern.structuring", "value": True, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "relationship.tenure_years", "value": 3, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.purpose", "value": "Unclear - multiple cash deposits", "label": "Stated Purpose"},
        ]
    },
    {
        "id": "shell-company-layering",
        "name": "Shell Company - BVI (ESCALATE)",
        "description": "Funds moving through shell company in tax haven with unclear ownership.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["BVI entity", "Missing docs", "$1.6M wire"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "VG", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 1632000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "SG", "label": "Destination Country"},
            {"field": "pattern.layering", "value": True, "label": "Layering Pattern"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": False, "label": "Beneficial Ownership Clear"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "relationship.tenure_years", "value": 0.3, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 4, "label": "Transaction Count"},
        ]
    },

    # ============== EDGE CASES (Boundary conditions) ==============
    {
        "id": "pep-plus-adverse-media",
        "name": "PEP + Adverse Media (EDGE)",
        "description": "Foreign PEP with adverse media linking to money laundering. Tests corroboration.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["PEP flag Y", "Adverse media MLTF", "Missing docs"],
        "facts": [
            {"field": "customer.pep_flag", "value": True, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "BR", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 476000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CH", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 92, "label": "Match Score"},
            {"field": "screening.list_type", "value": "ADVERSE_MEDIA", "label": "List Type"},
            {"field": "screening.mltf_linked", "value": True, "label": "Linked to Money Laundering"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "confirmed_mltf", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": True, "label": "Adverse Media"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 4, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 2, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Investment - unclear vehicle", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ]
    },
    {
        "id": "crypto-high-risk-corridor",
        "name": "Crypto to Wire - UAE (EDGE)",
        "description": "Crypto conversion to wire through high-risk jurisdiction.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["Crypto source", "UAE destination", "Unverified funds"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 102000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CRYPTO", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "AE", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 2, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 3, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Crypto liquidation - personal", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ]
    },
    {
        "id": "velocity-spike",
        "name": "10x Velocity Spike (EDGE)",
        "description": "Long-term customer with sudden 10x increase in transaction volume.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["12yr customer", "10x volume spike", "Missing docs"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 850000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CN", "label": "Destination Country"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "pattern.multiplier", "value": 10, "label": "Volume Multiplier"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 12, "label": "Relationship Tenure (Years)"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "transaction.count", "value": 15, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Trade payments - new supplier", "label": "Stated Purpose"},
            {"field": "docs.ownership_clear", "value": True, "label": "Beneficial Ownership Clear"},
        ]
    },
    {
        "id": "beneficial-owner-pep",
        "name": "Hidden PEP Owner (EDGE)",
        "description": "Corporate entity with undisclosed PEP beneficial owner discovered in screening.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["Cyprus entity", "Hidden PEP owner", "$2.9M to Swiss bank"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Customer PEP Flag"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CY", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 2900000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CH", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 88, "label": "Match Score"},
            {"field": "screening.list_type", "value": "PEP", "label": "List Type"},
            {"field": "screening.beneficial_owner_pep", "value": True, "label": "Beneficial Owner is PEP"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": False, "label": "Beneficial Ownership Clear"},
            {"field": "relationship.tenure_years", "value": 0.5, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 2, "label": "Transaction Count"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": True, "label": "Layering Pattern"},
        ]
    },

    # ============== STRESS TEST CASES (10 additional scenarios) ==============

    # ── PASS: Dormant account, low value, benign reactivation ──
    {
        "id": "dormant-account-reactivation",
        "name": "Dormant Account Reactivation (PASS)",
        "description": "Long-dormant individual account reactivated with small cash deposit. No risk indicators.",
        "category": "PASS",
        "expected_outcome": "pass",
        "key_facts": ["Dormant 18 months", "$3,200 deposit", "8-year relationship"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 3200, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CASH", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 8, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Account reactivation deposit", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── PASS: Cash-intensive business, routine LCTR ──
    {
        "id": "cash-intensive-lctr",
        "name": "Cash-Intensive Business - LCTR (PASS)",
        "description": "Restaurant depositing $15K cash. Known cash-intensive industry. Routine large cash handling.",
        "category": "PASS",
        "expected_outcome": "pass",
        "key_facts": ["Restaurant (cash-intensive)", "$15K cash deposit", "5-year relationship"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 15000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CASH", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 5, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Weekly restaurant cash deposit", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── ESCALATE: Exact sanctions match (SEMA) ──
    {
        "id": "sanctions-exact-match",
        "name": "Sanctions Exact Match - SEMA (ESCALATE)",
        "description": "Corporate wire to SEMA-listed entity. Exact match. Mandatory hard stop.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["SEMA exact match", "$50K wire", "Sanctioned jurisdiction"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 50000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "IR", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 100, "label": "Match Score"},
            {"field": "screening.list_type", "value": "SEMA", "label": "List Type"},
            {"field": "screening.sanctions_match", "value": True, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 0.5, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── EDGE: Domestic PEP, routine mortgage payment ──
    {
        "id": "domestic-pep-routine",
        "name": "Domestic PEP - Mortgage (EDGE)",
        "description": "Provincial PEP making routine mortgage payment. Long relationship, fully documented. PEP status triggers EDD by classifier sovereignty.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["Domestic PEP", "$2,800 mortgage", "12-year relationship"],
        "facts": [
            {"field": "customer.pep_flag", "value": True, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 2800, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "EFT", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 100, "label": "Match Score"},
            {"field": "screening.list_type", "value": "PEP", "label": "List Type"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 12, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Monthly mortgage payment", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── ESCALATE: Classic structuring — three same-day deposits ──
    {
        "id": "structuring-three-deposits",
        "name": "Structuring - Three Same-Day Deposits (ESCALATE)",
        "description": "New customer, three same-day cash deposits just under $10K at different branches.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["3x same-day cash", "$9.5K/$9.2K/$9.8K", "New customer (3 months)"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 9500, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "CASH", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "transaction.count", "value": 3, "label": "Transaction Count"},
            {"field": "pattern.structuring", "value": True, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 0.25, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.purpose", "value": "Unclear - multiple cash deposits same day", "label": "Stated Purpose"},
        ],
    },

    # ── EDGE: Trade finance with unusual documentation ──
    {
        "id": "trade-finance-unusual-docs",
        "name": "Trade Finance - Unusual Docs (EDGE)",
        "description": "Importer LC with vague goods description and inconsistent pricing. Profile deviation.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["$2.3M letter of credit", "Vague goods description", "Pricing inconsistency"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 2300000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "TR", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 3, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Letter of credit - import goods", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
            {"field": "trade.goods_description", "value": "vague", "label": "Goods Description Quality"},
            {"field": "trade.pricing_consistent", "value": False, "label": "Pricing Consistent"},
            {"field": "trade.is_letter_of_credit", "value": True, "label": "Letter of Credit"},
        ],
    },

    # ── PASS: Profile deviation with complete evidence ──
    {
        "id": "profile-deviation-complete-evidence",
        "name": "Profile Deviation - Complete Evidence (PASS)",
        "description": "First international wire but all evidence present including stated purpose. Clean profile.",
        "category": "PASS",
        "expected_outcome": "pass",
        "key_facts": ["First international wire", "All 27 fields present", "Property purchase"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 45000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "PT", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 6, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Property purchase deposit - Portugal", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── EDGE: Adverse media — unconfirmed fraud investigation ──
    {
        "id": "adverse-media-unconfirmed",
        "name": "Adverse Media - Unconfirmed (EDGE)",
        "description": "News article mentioning fraud investigation. Not confirmed, no charges. Clean profile otherwise.",
        "category": "EDGE",
        "expected_outcome": "escalate",
        "key_facts": ["Adverse media (unconfirmed)", "$75K domestic wire", "No charges filed"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 75000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "CA", "label": "Destination Country"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.match_score", "value": 75, "label": "Match Score"},
            {"field": "screening.list_type", "value": "ADVERSE_MEDIA", "label": "List Type"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "unconfirmed", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": True, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 4, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Investment - brokerage transfer", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },

    # ── ESCALATE: MSB with multiple red flags ──
    {
        "id": "multiple-flags-commercial-exit",
        "name": "MSB - Multiple Red Flags (ESCALATE)",
        "description": "Money service business with shell company indicators, rapid movement, third-party payments, and prior closure.",
        "category": "ESCALATE",
        "expected_outcome": "escalate",
        "key_facts": ["MSB client", "Shell + rapid + 3rd-party", "Prior account closure"],
        "facts": [
            {"field": "customer.pep_flag", "value": False, "label": "Is PEP"},
            {"field": "customer.type", "value": "CORP", "label": "Customer Type"},
            {"field": "customer.residence", "value": "CA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 180000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "NG", "label": "Destination Country"},
            {"field": "pattern.layering", "value": True, "label": "Layering Pattern"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": True, "label": "Velocity Spike"},
            {"field": "screening.match_count", "value": 0, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": False, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": False, "label": "Source of Funds Verified"},
            {"field": "docs.ownership_clear", "value": False, "label": "Beneficial Ownership Clear"},
            {"field": "flag.shell_company", "value": True, "label": "Shell Company Indicators"},
            {"field": "flag.third_party", "value": True, "label": "Third-Party Payments"},
            {"field": "prior.account_closures", "value": True, "label": "Prior Account Closure"},
            {"field": "relationship.tenure_years", "value": 2, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 5, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Supplier payments - unclear beneficiary", "label": "Stated Purpose"},
        ],
    },

    # ── EDGE: Foreign PEP, large wire, fully documented ──
    {
        "id": "pep-foreign-large-wire-clean",
        "name": "Foreign PEP - Large Wire Clean (EDGE)",
        "description": "Senior foreign government official, $320K wire, but long relationship and fully documented diplomatic salary.",
        "category": "EDGE",
        "expected_outcome": "pass",
        "key_facts": ["Foreign PEP", "$320K wire", "Diplomatic salary documented"],
        "facts": [
            {"field": "customer.pep_flag", "value": True, "label": "Is PEP"},
            {"field": "customer.type", "value": "IND", "label": "Customer Type"},
            {"field": "customer.residence", "value": "SA", "label": "Residence Country"},
            {"field": "transaction.amount_cad", "value": 320000, "label": "Amount (CAD)"},
            {"field": "transaction.method", "value": "WIRE", "label": "Payment Method"},
            {"field": "transaction.destination", "value": "GB", "label": "Destination Country"},
            {"field": "screening.match_score", "value": 97, "label": "Match Score"},
            {"field": "screening.list_type", "value": "PEP", "label": "List Type"},
            {"field": "screening.match_count", "value": 1, "label": "Screening Matches"},
            {"field": "screening.sanctions_match", "value": False, "label": "Sanctions Match"},
            {"field": "screening.adverse_media_level", "value": "none", "label": "Adverse Media Level"},
            {"field": "screening.adverse_media", "value": False, "label": "Adverse Media"},
            {"field": "screening.mltf_linked", "value": False, "label": "Linked to Money Laundering"},
            {"field": "docs.complete", "value": True, "label": "Documentation Complete"},
            {"field": "docs.source_verified", "value": True, "label": "Source of Funds Verified"},
            {"field": "relationship.tenure_years", "value": 7, "label": "Relationship Tenure (Years)"},
            {"field": "transaction.count", "value": 1, "label": "Transaction Count"},
            {"field": "transaction.purpose", "value": "Property management fees - London residence", "label": "Stated Purpose"},
            {"field": "pattern.structuring", "value": False, "label": "Structuring Pattern Detected"},
            {"field": "pattern.velocity_spike", "value": False, "label": "Velocity Spike"},
            {"field": "pattern.layering", "value": False, "label": "Layering Pattern"},
        ],
    },
]


def get_demo_cases() -> list[dict]:
    """Return all demo cases for list view."""
    return [{
        "id": c["id"],
        "name": c["name"],
        "description": c["description"],
        "category": c["category"],
        "expected_verdict": c.get("expected_outcome", "unknown"),
        "expected_outcome": c.get("expected_outcome", "unknown"),
        "key_levers": c.get("key_facts", []),
        "key_facts": c.get("key_facts", []),
        "tags": [c["category"].lower()],
        "facts": [
            {"field_id": f["field"], "field": f["field"], "value": f["value"], "label": f.get("label", f["field"])}
            for f in c["facts"]
        ],
    } for c in DEMO_CASES]


def get_demo_case(case_id: str) -> dict | None:
    """Get a specific demo case by ID."""
    for case in DEMO_CASES:
        if case["id"] == case_id:
            return {
                "id": case["id"],
                "name": case["name"],
                "description": case["description"],
                "category": case["category"],
                "expected_verdict": case.get("expected_outcome", "unknown"),
                "expected_outcome": case.get("expected_outcome", "unknown"),
                "key_levers": case.get("key_facts", []),
                "key_facts": case.get("key_facts", []),
                "tags": [case["category"].lower()],
                "facts": [
                    {"field_id": f["field"], "field": f["field"], "value": f["value"], "label": f.get("label", f["field"])}
                    for f in case["facts"]
                ],
            }
    return None


def get_demo_cases_by_category(category: str) -> list[dict]:
    """Get demo cases filtered by category (PASS/ESCALATE/EDGE)."""
    return [c for c in DEMO_CASES if c["category"] == category]
